### ISSUE TITLE
Network can be unreliable

### ISSUE THREAD

**Issue by mt-sergio** [alpaca0984/currency-converter#20]
Hi Alpaca,
Can you create a PR introducing some code ensuring that `Net::HTTP.get` doesn't crash when we call `OpenExchangeRatesClient.new.fetch_currencies` ?

Network can be down, returns another status code or just timeout.

What do you think about this?

**Comment by MasaHirano** [comment]
Hi Sergio,

Thank you for your comment! And I see what you mean, so I'm considering it now.

At first, I thought that I would handle errors in `OpenExchangeRatesClient#fetch_currencies`, but it depends on situations that how errors should be treated. So I'm gonna handle errors where I call `OpenExchangeRatesClient#fetch_currencies`.

By the way, you gave me good advice that it's good for us to specify how long timeout will be and so on. So, how about using `Net::HTTP.start` instead of `Net::HTTP.get`? `Net::HTTP.start` can be specified detail behaviors. This page explains it.
https://ruby-doc.org/stdlib-2.5.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-start

After all, I image that I'm gonna change code like this.

Before:
```ruby 
class CurrencyConverter
  ...
  def self.currencies
    @currencies ||= JSON.parse(OpenExchangeRatesClient.new.fetch_currencies)
  end
```

After:
```ruby 
class CurrencyConverter
  ...
  def self.currencies
    @currencies ||= begin
      http_response = OpenExchangeRatesClient.new.fetch_currencies(read_timeout: 30)
      if response.is_a?(Net::HTTPOK)
        JSON.parse(http_response.body)
      end
    end
  end
```

What do you think about this? Any advices would be appreciated!

**Comment by mt-sergio** [comment]
This is something, but I cannot help you too much or would be unfair for other candidates.
Submit a PR as you consider you would submit to our production environment. My team will evaluate it and let me know what they think.

**Comment by MasaHirano** [comment]
@mt-sergio 
Ok, sure! I'm sorry but it was my habit, so never mind. I mean, I usually develop applications while communicating with my team members.

I write code what I'm confident and create PR!
